<a href="https://colab.research.google.com/github/iddadobroc/DSML_Group11_Clustering/blob/main/DSML_Group11.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Reach for Change

Part 1: Uncovering Donor Profiles Through Clustering
Data Science and Machine Learning Group Project 2025/2026

| Student #    | Name |
| :-------- | :------- |
| aaa  | 111    |
| bbb |   222   |
| ccc    | 333    |
| 20251105 | Kehinde Adewusi |

In [ ]:
import pandas as pd

In [ ]:

df = pd.read_csv('https://raw.githubusercontent.com/iddadobroc/DSML_Group11_Clustering/refs/heads/main/donors_descriptive.csv')
df.head()

,CONTROL_NUMBER,CARD_PROM_12,CHILDREN,DONOR_AGE,DONOR_GENDER,FILE_CARD_GIFT,FREQUENCY_STATUS_97NK,HOME_OWNER,INCOME_GROUP,LAST_GIFT_AMT,...,RECENT_AVG_CARD_GIFT_AMT,RECENT_AVG_GIFT_AMT,RECENT_CARD_RESPONSE_COUNT,RECENT_CARD_RESPONSE_PROP,RECENT_RESPONSE_COUNT,RECENT_RESPONSE_PROP,RECENT_STAR_STATUS,SES,URBANICITY,WEALTH_RATING
0,61745,4.0,2.000000,33.0,M,0.0,1.0,H,5.0,20.0,...,0.00,17.50,0.0,0.000,2.0,0.154,0.0,2,T,NaN
1,112703,3.0,-2.341107,NaN,F,1.0,1.0,U,NaN,15.0,...,15.00,15.00,1.0,0.250,1.0,0.100,0.0,3,R,NaN
2,166437,4.0,0.000000,74.0,F,7.0,3.0,H,4.0,10.0,...,0.00,10.67,0.0,0.000,3.0,0.231,1.0,1,U,NaN
3,170621,4.0,4.000000,61.0,M,13.0,1.0,H,6.0,11.0,...,10.00,10.00,2.0,0.286,2.0,0.111,0.0,1,U,NaN
4,44428,6.0,3.000000,75.0,M,3.0,4.0,H,3.0,7.0,...,5.67,5.40,3.0,0.600,5.0,0.500,0.0,2,C,NaN

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13560 entries, 0 to 13559
Data columns (total 40 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   CONTROL_NUMBER               13560 non-null  int64
 1   CARD_PROM_12                 13297 non-null  float64
 2   CHILDREN                     13289 non-null  float64
 3   DONOR_AGE                    9970 non-null   float64
 4   DONOR_GENDER                 13303 non-null  object
 5   FILE_CARD_GIFT               13292 non-null  float64
 6   FREQUENCY_STATUS_97NK        13296 non-null  float64
 7   HOME_OWNER                   13292 non-null  object
 8   INCOME_GROUP                 10273 non-null  float64
 9   LAST_GIFT_AMT                13296 non-null  float64
 10  LIFETIME_CARD_PROM           13289 non-null  float64
 11  LIFETIME_GIFT_AMOUNT         13288 non-null  float64
 12  LIFETIME_GIFT_COUNT          13304 non-null  float64
 13  LIFETIME_MAX_GIFT_AMT        13284 non-null  float64
 14  LIFETIME_MIN_GIFT_AMT        13297 non-null  float64
 15  LIFETIME_PROM                13286 non-null  float64
 16  MEDIAN_HOME_VALUE            13305 non-null  float64
 17  MEDIAN_HOUSEHOLD_INCOME      13309 non-null  float64
 18  MONTHS_SINCE_FIRST_GIFT      13282 non-null  float64
 19  MONTHS_SINCE_LAST_GIFT       13285 non-null  float64
 20  MONTHS_SINCE_LAST_PROM_RESP  13130 non-null  float64
 21  NUMBER_PROM_12               13288 non-null  float64
 22  PCT_ATTRIBUTE1               13284 non-null  float64
 23  PCT_ATTRIBUTE2               13304 non-null  float64
 24  PCT_ATTRIBUTE3               13278 non-null  float64
 25  PCT_ATTRIBUTE4               13293 non-null  float64
 26  PCT_OWNER_OCCUPIED           13297 non-null  float64
 27  PEP_STAR                     13295 non-null  float64
 28  PER_CAPITA_INCOME            13305 non-null  float64
 29  RECENCY_STATUS_96NK          13294 non-null  object
 30  RECENT_AVG_CARD_GIFT_AMT     13309 non-null  float64
 31  RECENT_AVG_GIFT_AMT          13292 non-null  float64
 32  RECENT_CARD_RESPONSE_COUNT   13282 non-null  float64
 33  RECENT_CARD_RESPONSE_PROP    13286 non-null  float64
 34  RECENT_RESPONSE_COUNT        13294 non-null  float64
 35  RECENT_RESPONSE_PROP         13308 non-null  float64
 36  RECENT_STAR_STATUS           13285 non-null  float64
 37  SES                          13274 non-null  object
 38  URBANICITY                   13282 non-null  object
 39  WEALTH_RATING                7291 non-null   float64
dtypes: float64(34), int64(1), object(5)
memory usage: 4.1+ MB

In [ ]:
df.shape

(13560, 40)

In [ ]:
df.isna().sum()

CONTROL_NUMBER                    0
CARD_PROM_12                    263
CHILDREN                        271
DONOR_AGE                      3590
DONOR_GENDER                    257
FILE_CARD_GIFT                  268
FREQUENCY_STATUS_97NK           264
HOME_OWNER                      268
INCOME_GROUP                   3287
LAST_GIFT_AMT                   264
LIFETIME_CARD_PROM              271
LIFETIME_GIFT_AMOUNT            272
LIFETIME_GIFT_COUNT             256
LIFETIME_MAX_GIFT_AMT           276
LIFETIME_MIN_GIFT_AMT           263
LIFETIME_PROM                   274
MEDIAN_HOME_VALUE               255
MEDIAN_HOUSEHOLD_INCOME         251
MONTHS_SINCE_FIRST_GIFT         278
MONTHS_SINCE_LAST_GIFT          275
MONTHS_SINCE_LAST_PROM_RESP     430
NUMBER_PROM_12                  272
PCT_ATTRIBUTE1                  276
PCT_ATTRIBUTE2                  256
PCT_ATTRIBUTE3                  282
PCT_ATTRIBUTE4                  267
PCT_OWNER_OCCUPIED              263
PEP_STAR                        265
PER_CAPITA_INCOME               255
RECENCY_STATUS_96NK             266
RECENT_AVG_CARD_GIFT_AMT        251
RECENT_AVG_GIFT_AMT             268
RECENT_CARD_RESPONSE_COUNT      278
RECENT_CARD_RESPONSE_PROP       274
RECENT_RESPONSE_COUNT           266
RECENT_RESPONSE_PROP            252
RECENT_STAR_STATUS              275
SES                             286
URBANICITY                      278
WEALTH_RATING                  6269
dtype: int64

In [ ]:
df

,CONTROL_NUMBER,CARD_PROM_12,CHILDREN,DONOR_AGE,DONOR_GENDER,FILE_CARD_GIFT,FREQUENCY_STATUS_97NK,HOME_OWNER,INCOME_GROUP,LAST_GIFT_AMT,...,RECENT_AVG_CARD_GIFT_AMT,RECENT_AVG_GIFT_AMT,RECENT_CARD_RESPONSE_COUNT,RECENT_CARD_RESPONSE_PROP,RECENT_RESPONSE_COUNT,RECENT_RESPONSE_PROP,RECENT_STAR_STATUS,SES,URBANICITY,WEALTH_RATING
0,61745,4.0,2.000000,33.0,M,0.0,1.0,H,5.0,20.0,...,0.00,17.50,0.0,0.000,2.0,0.154,0.0,2,T,NaN
1,112703,3.0,-2.341107,NaN,F,1.0,1.0,U,NaN,15.0,...,15.00,15.00,1.0,0.250,1.0,0.100,0.0,3,R,NaN
2,166437,4.0,0.000000,74.0,F,7.0,3.0,H,4.0,10.0,...,0.00,10.67,0.0,0.000,3.0,0.231,1.0,1,U,NaN
3,170621,4.0,4.000000,61.0,M,13.0,1.0,H,6.0,11.0,...,10.00,10.00,2.0,0.286,2.0,0.111,0.0,1,U,NaN
4,44428,6.0,3.000000,75.0,M,3.0,4.0,H,3.0,7.0,...,5.67,5.40,3.0,0.600,5.0,0.500,0.0,2,C,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13555,34797,5.0,0.000000,84.0,M,6.0,1.0,H,6.0,10.0,...,10.00,10.00,1.0,0.100,2.0,NaN,6.0,2,C,3.0
13556,7550,7.0,1.000000,86.0,F,16.0,3.0,H,2.0,10.0,...,10.00,7.50,2.0,0.222,4.0,0.211,1.0,2,U,3.0
13557,115215,6.0,2.000000,NaN,M,2.0,3.0,U,1.0,10.0,...,8.50,9.00,2.0,0.250,NaN,0.235,0.0,2,T,NaN
13558,88067,6.0,1.000000,NaN,M,2.0,2.0,U,NaN,15.0,...,10.00,10.00,2.0,0.500,2.0,0.286,0.0,1,S,NaN
13559,45722,4.0,3.000000,74.0,F,12.0,2.0,H,2.0,15.0,...,15.00,17.50,1.0,0.125,2.0,0.133,1.0,2,T,NaN

In [ ]:
df1=df.copy()

In [ ]:
df1.drop(columns=["WEALTH_RATING"], inplace = True)

In [ ]:
df1

,CONTROL_NUMBER,CARD_PROM_12,CHILDREN,DONOR_AGE,DONOR_GENDER,FILE_CARD_GIFT,FREQUENCY_STATUS_97NK,HOME_OWNER,INCOME_GROUP,LAST_GIFT_AMT,...,RECENCY_STATUS_96NK,RECENT_AVG_CARD_GIFT_AMT,RECENT_AVG_GIFT_AMT,RECENT_CARD_RESPONSE_COUNT,RECENT_CARD_RESPONSE_PROP,RECENT_RESPONSE_COUNT,RECENT_RESPONSE_PROP,RECENT_STAR_STATUS,SES,URBANICITY
0,61745,4.0,2.000000,33.0,M,0.0,1.0,H,5.0,20.0,...,A,0.00,17.50,0.0,0.000,2.0,0.154,0.0,2,T
1,112703,3.0,-2.341107,NaN,F,1.0,1.0,U,NaN,15.0,...,N,15.00,15.00,1.0,0.250,1.0,0.100,0.0,3,R
2,166437,4.0,0.000000,74.0,F,7.0,3.0,H,4.0,10.0,...,NaN,0.00,10.67,0.0,0.000,3.0,0.231,1.0,1,U
3,170621,4.0,4.000000,61.0,M,13.0,1.0,H,6.0,11.0,...,A,10.00,10.00,2.0,0.286,2.0,0.111,0.0,1,U
4,44428,6.0,3.000000,75.0,M,3.0,4.0,H,3.0,7.0,...,N,5.67,5.40,3.0,0.600,5.0,0.500,0.0,2,C
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13555,34797,5.0,0.000000,84.0,M,6.0,1.0,H,6.0,10.0,...,A,10.00,10.00,1.0,0.100,2.0,NaN,6.0,2,C
13556,7550,7.0,1.000000,86.0,F,16.0,3.0,H,2.0,10.0,...,S,10.00,7.50,2.0,0.222,4.0,0.211,1.0,2,U
13557,115215,6.0,2.000000,NaN,M,2.0,3.0,U,1.0,10.0,...,A,8.50,9.00,2.0,0.250,NaN,0.235,0.0,2,T
13558,88067,6.0,1.000000,NaN,M,2.0,2.0,U,NaN,15.0,...,N,10.00,10.00,2.0,0.500,2.0,0.286,0.0,1,S
13559,45722,4.0,3.000000,74.0,F,12.0,2.0,H,2.0,15.0,...,S,15.00,17.50,1.0,0.125,2.0,0.133,1.0,2,T

In [ ]:
df1.set_index("CONTROL_NUMBER", inplace = True)

In [ ]:
df1

,CARD_PROM_12,CHILDREN,DONOR_AGE,DONOR_GENDER,FILE_CARD_GIFT,FREQUENCY_STATUS_97NK,HOME_OWNER,INCOME_GROUP,LAST_GIFT_AMT,LIFETIME_CARD_PROM,...,RECENCY_STATUS_96NK,RECENT_AVG_CARD_GIFT_AMT,RECENT_AVG_GIFT_AMT,RECENT_CARD_RESPONSE_COUNT,RECENT_CARD_RESPONSE_PROP,RECENT_RESPONSE_COUNT,RECENT_RESPONSE_PROP,RECENT_STAR_STATUS,SES,URBANICITY
CONTROL_NUMBER,,,,,,,,,,,,,,,,,,,,,
61745,4.0,2.000000,33.0,M,0.0,1.0,H,5.0,20.0,9.0,...,A,0.00,17.50,0.0,0.000,2.0,0.154,0.0,2,T
112703,3.0,-2.341107,NaN,F,1.0,1.0,U,NaN,15.0,6.0,...,N,15.00,15.00,1.0,0.250,1.0,0.100,0.0,3,R
166437,4.0,0.000000,74.0,F,7.0,3.0,H,4.0,10.0,17.0,...,NaN,0.00,10.67,0.0,0.000,3.0,0.231,1.0,1,U
170621,4.0,4.000000,61.0,M,13.0,1.0,H,6.0,11.0,28.0,...,A,10.00,10.00,2.0,0.286,2.0,0.111,0.0,1,U
44428,6.0,3.000000,75.0,M,3.0,4.0,H,3.0,7.0,9.0,...,N,5.67,5.40,3.0,0.600,5.0,0.500,0.0,2,C
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34797,5.0,0.000000,84.0,M,6.0,1.0,H,6.0,10.0,32.0,...,A,10.00,10.00,1.0,0.100,2.0,NaN,6.0,2,C
7550,7.0,1.000000,86.0,F,16.0,3.0,H,2.0,10.0,33.0,...,S,10.00,7.50,2.0,0.222,4.0,0.211,1.0,2,U
115215,6.0,2.000000,NaN,M,2.0,3.0,U,1.0,10.0,12.0,...,A,8.50,9.00,2.0,0.250,NaN,0.235,0.0,2,T
88067,6.0,1.000000,NaN,M,2.0,2.0,U,NaN,15.0,8.0,...,N,10.00,10.00,2.0,0.500,2.0,0.286,0.0,1,S
45722,4.0,3.000000,74.0,F,12.0,2.0,H,2.0,15.0,26.0,...,S,15.00,17.50,1.0,0.125,2.0,0.133,1.0,2,T